# docker-compose.yml
version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped